Update pip-ubuntu-22.yml

diff --git a/.github/workflows/pip-ubuntu-22.yml b/.github/workflows/pip-ubuntu-22.yml
--- a/.github/workflows/pip-ubuntu-22.yml
+++ b/.github/workflows/pip-ubuntu-22.yml
@@ -37,9 +37,28 @@ jobs:
 
       - name: Build and install
         run: pip install --verbose .
-      - name: Build and install
-        run: pip install --upgrade --force-reinstall .
-      - name: Deploy Docs 
-        uses: JamesIves/github-pages-deploy-action@v4
+
+      - uses: ammaraskar/sphinx-action@master
         with:
-          folder: build/temp.linux-x86_64-cpython-39/doc/sphinx # The folder the action should deploy
+         docs-folder: "doc/"
+      # Publish built docs to gh-pages branch.
+      # ===============================
+      - name: Commit documentation changes
+        run: |
+            git clone https://github.com/jbpezent/depreltest.git --branch gh-pages --single-branch gh-pages
+            cp -r docs/_build/html/* gh-pages/
+            cd gh-pages
+            touch .nojekyll
+            git config --local user.email "action@github.com"
+            git config --local user.name "GitHub Action"
+            git add .
+            git commit -m "Update documentation" -a || true
+            # The above command will fail if no changes were present, so we ignore
+            # that.
+      - name: Push changes
+        uses: ad-m/github-push-action@master
+        with:
+          branch: gh-pages
+          directory: gh-pages
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+    # ===============================
